# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master  # Indentation level increased by two spaces

pool:
  vmImage: ubuntu-latest  # Consistent indentation level

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'  # Consistent indentation level

  - task: Bash@3
    displayName: "Snyk_SCA_Scanning"
    inputs:
      targetType: 'inline'
      script: |
        echo "----------Download Latest Snyk CLI-----------"
        curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1159.0/snyk-linux"
        chmod +x snyk
        ls -lrt
        echo "----------Authenticating Snyk-----------"
        ./snyk auth $(SNYK-TOKEN)
        echo "----------Snyk Monitor-----------"
        ./snyk monitor --all-projects
        echo "----------Snyk Scanning-----------"
        ./snyk test --all-projects
         failOnStderr: false